[profile.default]
src = "src"
test = "test"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
viaIR = true

remappings = [
  "forge-std/=lib/forge-std/src/",

  "@openzeppelin/=lib/openzeppelin-contracts/",

  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",

  "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/src/",
  "uniswap-hooks/=lib/uniswap-hooks/src/",

  "solmate/=lib/solmate/src/",

  "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity/",
]

[fmt]
line_length = 100
tab_width = 4

[lint]
exclude_lints = ["mixed-case-variable"]
